name: egg
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - brotlipy=0.7.0=py36h27cfd23_1003
  - ca-certificates=2021.1.19=h06a4308_0
  - certifi=2020.12.5=py36h06a4308_0
  - cffi=1.14.4=py36h261ae71_0
  - chardet=4.0.0=py36h06a4308_1003
  - click=7.1.2=py_0
  - cloudpickle=1.6.0=py_0
  - cryptography=3.3.1=py36h3c74f83_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py36h7b6447c_0
  - dask-core=2021.1.1=pyhd3eb1b0_0
  - decorator=4.4.2=pyhd3eb1b0_0
  - freetype=2.10.4=h7ca028e_0
  - h5py=2.10.0=py36hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=67.1=he1b5a44_0
  - idna=2.10=pyhd3eb1b0_0
  - imageio=2.9.0=py_0
  - intel-openmp=2020.2=254
  - joblib=0.17.0=py_0
  - jpeg=9d=h36c2ea0_0
  - kiwisolver=1.3.1=py36h51d7077_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.9.0=7_openblas
  - libcblas=3.9.0=7_openblas
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.5.0=h14aa051_18
  - libgfortran4=7.5.0=h14aa051_18
  - liblapack=3.9.0=7_openblas
  - libopenblas=0.3.12=pthreads_hb3c22a3_1
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.9=h648cc4a_1002
  - matplotlib=3.2.2=1
  - matplotlib-base=3.2.2=py36h5fdd944_1
  - mkl=2020.2=256
  - ncurses=6.2=he6710b0_1
  - networkx=2.5=py_0
  - ninja=1.10.2=py36hff7bd54_0
  - nltk=3.5=py_0
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1i=h27cfd23_0
  - pip=20.3.3=py36h06a4308_0
  - pycparser=2.20=py_2
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysocks=1.7.1=py36h06a4308_0
  - python=3.6.12=hcff3b4d_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytorch=1.4.0=py3.6_cuda10.1.243_cudnn7.6.3_0
  - pywavelets=1.1.1=py36h7b6447c_2
  - pyyaml=5.4.1=py36h27cfd23_1
  - readline=8.0=h7b6447c_0
  - regex=2020.10.15=py36h7b6447c_0
  - requests=2.25.1=pyhd3eb1b0_0
  - scikit-image=0.17.2=py36hdf5156a_0
  - scikit-learn=0.23.2=py36hb6e6923_3
  - setuptools=51.3.3=py36h06a4308_4
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.33.0=h62c20be_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tifffile=2020.10.1=py36hdd07704_2
  - tk=8.6.10=hbc83047_0
  - toolz=0.11.1=pyhd3eb1b0_0
  - torchtext=0.6.0=py_1
  - tornado=6.1=py36h1d69622_0
  - tqdm=4.50.2=py_0
  - urllib3=1.26.3=pyhd3eb1b0_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - attrs==20.3.0
    - colorama==0.4.4
    - commonmark==0.9.1
    - dataclasses==0.8
    - editdistance==0.5.3
    - future==0.18.2
    - importlib-metadata==3.4.0
    - iniconfig==1.1.1
    - numpy==1.19.5
    - packaging==20.8
    - pillow==8.1.0
    - pluggy==0.13.1
    - py==1.10.0
    - pygments==2.7.4
    - pytest==6.2.1
    - rich==9.8.2
    - scipy==1.5.4
    - toml==0.10.2
    - torch==1.2.0
    - torchvision==0.4.0
    - typing-extensions==3.7.4.3
    - zipp==3.4.0
prefix: /storage/raid1/homedirs/mitja.nikolaus/anaconda3/envs/egg
